security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email # Login using email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            entry_point: form_login  # ✅ Tell Symfony to use form_login as the default
            form_login:
                login_path: login
                check_path: login
                enable_csrf: true # ✅ Use this instead of csrf_token_generator
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
                default_target_path: userspace # Redirect after login
                username_parameter: email  # ✅ Must match your form field
                password_parameter: password
            logout:
                path: logout
                target: login # Redirect after logout
            custom_authenticator: App\Security\AppCustomAuthenticator

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # by default, the feature is enabled by checking a checkbox in the
                # login form, uncomment the following line to always enable it.
                #always_remember_me: true

    access_control:
        - { path: ^/userspace, roles: ROLE_USER }
        - { path: ^/, roles: PUBLIC_ACCESS }
