<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250406135010 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create image and shop_request tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, alt VARCHAR(255) DEFAULT NULL, is_main BOOLEAN NOT NULL, created TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by INT DEFAULT NULL, id_shop_request_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C53D045FD153960B ON image (id_shop_request_id)');
        $this->addSql('CREATE TABLE shop_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_name VARCHAR(255) NOT NULL, price NUMERIC(10, 0) NOT NULL, product_url VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045FD153960B FOREIGN KEY (id_shop_request_id) REFERENCES shop_request (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE image DROP CONSTRAINT FK_C53D045FD153960B');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE shop_request');
    }
}
