<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250418084844 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'add state entity';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
                CREATE TABLE state (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, country_id INT NOT NULL, PRIMARY KEY(id))
            SQL);
        $this->addSql(<<<'SQL'
                CREATE INDEX IDX_A393D2FBF92F3E70 ON state (country_id)
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE state ADD CONSTRAINT FK_A393D2FBF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE city ADD state_id INT DEFAULT NULL
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE city ALTER country_id DROP NOT NULL
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE city ADD CONSTRAINT FK_2D5B02345D83CC1 FOREIGN KEY (state_id) REFERENCES state (id) NOT DEFERRABLE INITIALLY IMMEDIATE
            SQL);
        $this->addSql(<<<'SQL'
                CREATE INDEX IDX_2D5B02345D83CC1 ON city (state_id)
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
                ALTER TABLE state DROP CONSTRAINT FK_A393D2FBF92F3E70
            SQL);
        $this->addSql(<<<'SQL'
                DROP TABLE state
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE city DROP CONSTRAINT FK_2D5B02345D83CC1
            SQL);
        $this->addSql(<<<'SQL'
                DROP INDEX IDX_2D5B02345D83CC1
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE city DROP state_id
            SQL);
        $this->addSql(<<<'SQL'
                ALTER TABLE city ALTER country_id SET NOT NULL
            SQL);
    }
}
